auth:
    tokens:
        refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOSIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiUkVGUkVTSCIsImV4cCI6MTY1NTcwNDI1OSwiaWF0IjoxNjU1NjE3ODU5LCJpc3MiOiJrbmlnaHRoYWNrcyJ9.Cnl3foiPbmEWnBPT_tLMsptJWQyPbb5POeZs9cr5ANE
        access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOSIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiQUNDRVNTIiwiZXhwIjoxNjU1NjE5NjU5LCJpYXQiOjE2NTU2MTc4NTksImlzcyI6ImtuaWdodGhhY2tzIn0.lXETYz9eOm0L01ZlTmM9yWA_HgdnxMDYdPErXEgM8js
