auth:
    tokens:
        refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNCIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiUkVGUkVTSCIsImV4cCI6MTY1NTY2NzAzODI5NywiaWF0IjoxNjU1NTgwNjM4Mjk3LCJpc3MiOiJrbmlnaHRoYWNrcyJ9.XfIfQCHH0WRpOV6-JL72t2O4R4ofqUgm3bNlC5hnfYk
        access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNCIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiQUNDRVNTIiwiZXhwIjoxNjU1NTgyNDM4Mjk3LCJpYXQiOjE2NTU1ODA2MzgyOTcsImlzcyI6ImtuaWdodGhhY2tzIn0.07mKij_7ZrTEnmAbwspWSWVBBS7lk7IW6zCBKcPDqII
