auth:
    tokens:
        refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOSIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiUkVGUkVTSCIsImV4cCI6MTY1NTc1NjAzMywiaWF0IjoxNjU1NjY5NjMzLCJpc3MiOiJrbmlnaHRoYWNrcyJ9.XISwy_cG6Tv_andvC_QYbHupsl7epn_VaMymUrhXYg8
        access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOSIsInJvbGUiOiJOT1JNQUwiLCJ0eXBlIjoiQUNDRVNTIiwiZXhwIjoxNjU1NjcxNDMzLCJpYXQiOjE2NTU2Njk2MzMsImlzcyI6ImtuaWdodGhhY2tzIn0.yK6YUNUXCzB-D8JYnt3K6uUDYBllEsvSlhNJT36xxaw
