name: Release

# Credit to https://github.com/KnightHacks/hackathon-2021-backend

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (semver: 1.2.3)'
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: ${{ env.VERSION }}

  create-release:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create release branch
        run: git checkout -b release/${{ env.VERSION }}

      - name: Init git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ env.VERSION }}

      - name: Commit changelog and version in package
        id: make-commit
        run: |
          git add CHANGELOG.md
          git commit --message "Prepare release ${{ env.VERSION }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push commit
        run: |
          git push origin release/${{ env.VERSION }}
      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ env.VERSION }}
          base: main
          title: ${{ env.VERSION }} into main
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            This PR was created when the Create Release workflow was run.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
      - name: Create pull request into development
        uses: thomaseizinger/create-pull-request@1.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ env.VERSION }}
          base: development
          title: ${{ env.VERSION }} into development
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            This PR was created when the Create Release workflow was run.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
